### PR TITLE
Minor updates to release notes, and multi-buildpack content

### PR DESCRIPTION
**Pull request by okilker**

### CODE REVIEW

**Comment by tehall16** [comment]
@okilker : Is this still relevant?

**Comment by okilker** [comment]
Hi @tehall16, yes, is it possible to merge everything but docs-content/index.html.md.erb?

**Comment by pavankrish123** [comment]
Fixed merge conflicts

**Comment by tehall16** [comment]
Merged, thanks for looking at the merge conflicts @pavankrish123

**Pull request merged**
