### PR TITLE
Nomenclature

### PR DESCRIPTION
**Pull request by okilker**
@pavankrish123 and @jeffaholmes @jknostman3 , please review.

### CODE REVIEW

**Comment by jknostman3** [comment]
@okilker I am not sure the first sentence that was changed on the index makes sense. It says that the tile allows you to deploy AppDynamics -Monitored apps onto PivNet. But PivNet is just our marketplace where users download software. People deploy applications onto Pivotal Cloud Foundry and the tile allows them to monitor those apps with AppDynamics.

**Comment by jeffaholmes** [comment]
@okilker @jknostman3  good point, I'd say something like: "...allows you to easily deploy AppDynamics-monitored applications in PCF using an AppDynamics marketplace service."

**Comment by okilker** [comment]
Hi there, @jeffaholmes and @jknostman3 thanks for your comments! I've added the info, and hope it accurately reflects your input.

I'm having some difficulty previewing the docs locally, (gem issue).  I'm also seeing a merge conflict based on dates. Is this an auto-update feature? Meaning I'm seeing a date change from Oct 1 to Oct 30, today's date.

`.rvm/gems/ruby-2.3.0/gems/bundler-1.16.4/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path': can't find executable bookbinder for gem bookbindery. bookbindery is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)`

this-branch-has-conflicts

**Comment by jknostman3** [comment]
@okilker Thanks!

**Pull request merged**
