### PR TITLE
Word tweaks, plus added the following section to installing.html.md.erb: Set Permissions for AppDynamics User Account to Publish Dashboards.

### PR DESCRIPTION
**Pull request by douglas-j-bothwell**

### CODE REVIEW

**Comment by douglas-j-bothwell** [comment]
Doug Bothwell: My apologies for the conflicts in this branch. There are no time-sensitive updates in this pull request.  I will resolve these conflicts by the end of today (Friday August 3).

**Comment by douglas-j-bothwell** [comment]
I have resolved the conflicts in this branch. If you have issues with this Pull Request please me and pavankrish123  know. Thanks!

**Comment by pavankrish123** [comment]
@jknostman3  can you please review this? and let us know if you have any more suggestions, the PR is primarily fixing typos and some proper rendering

**Comment by jknostman3** [comment]
@douglas-j-bothwell Thanks!

**Pull request merged**
